-- Seed products table with data from products.json
INSERT INTO products (id, name, category, price, unit, image, description, origin) VALUES
('cashew', 'Cashew', 'Dry Fruits', 450.00, 'per kg', '/products/cashew.jpg', 'Premium cashews', 'India'),
('badam-pisin', 'Badam Pisin', 'Dry Fruits', 350.00, 'per kg', '/products/badam-pisin.jpg', 'Almond paste', 'India'),
('kishmish', 'Kishmish', 'Dry Fruits', 280.00, 'per kg', '/products/kishmish.jpg', 'Dried grapes', 'India'),
('raw-peanut', 'Raw Peanut', 'Dry Fruits', 150.00, 'per kg', '/products/raw-peanut.jpg', 'Raw peanuts', 'India'),
('almond', 'Almond', 'Dry Fruits', 500.00, 'per kg', '/products/almond.jpg', 'Premium almonds', 'India'),
('dry-figs', 'Dry Figs', 'Dry Fruits', 400.00, 'per kg', '/products/dry-figs.jpg', 'Dried figs', 'Turkey'),
('star-anise', 'Star Anise', 'Spices', 200.00, 'per 100g', '/products/star-anise.jpg', 'Star shaped spice', 'Vietnam'),
('cardamom', 'Cardamom', 'Spices', 300.00, 'per 100g', '/products/cardamom.jpg', 'Green cardamom', 'India'),
('fenugreek', 'Fenugreek', 'Spices', 120.00, 'per 100g', '/products/fenugreek.jpg', 'Methi seeds', 'India'),
('sabja-seed', 'Sabja Seed', 'Seeds', 180.00, 'per 100g', '/products/sabja-seed.jpg', 'Basil seeds', 'India'),
('mustard-seed', 'Mustard Seed', 'Seeds', 100.00, 'per 100g', '/products/mustard-seed.jpg', 'Brown mustard', 'India'),
('clove', 'Clove', 'Spices', 250.00, 'per 100g', '/products/clove.jpg', 'Dried cloves', 'Indonesia'),
('ajwain-seeds', 'Ajwain Seeds', 'Seeds', 140.00, 'per 100g', '/products/ajwain-seeds.jpg', 'Carom seeds', 'India'),
('white-poppy-seeds', 'White Poppy Seeds', 'Seeds', 220.00, 'per 100g', '/products/white-poppy-seeds.jpg', 'Khus khus', 'India'),
('black-sesame-seeds', 'Black Sesame Seeds', 'Seeds', 190.00, 'per 100g', '/products/black-sesame-seeds.jpg', 'Kala til', 'India'),
('cumin-seeds', 'Cumin Seeds', 'Spices', 160.00, 'per 100g', '/products/cumin-seeds.jpg', 'Jeera', 'India'),
('green-peas', 'Green Peas', 'Legumes', 130.00, 'per kg', '/products/green-peas.jpg', 'Dried green peas', 'India'),
('toor-dal', 'Toor Dal', 'Legumes', 140.00, 'per kg', '/products/toor-dal.jpg', 'Pigeon peas', 'India'),
('moong-dal', 'Moong Dal', 'Legumes', 120.00, 'per kg', '/products/moong-dal.jpg', 'Mung beans', 'India'),
('green-gram', 'Green Gram', 'Legumes', 125.00, 'per kg', '/products/green-gram.jpg', 'Whole moong', 'India'),
('round-red-chilli', 'Round Red Chilli', 'Spices', 180.00, 'per 100g', '/products/round-red-chilli.jpg', 'Red chilli powder', 'India'),
('jaggery-balls', 'Jaggery Balls', 'Sweeteners', 90.00, 'per kg', '/products/jaggery-balls.jpg', 'Organic jaggery', 'India'),
('multani-mitti', 'Multani Mitti', 'Specialty', 80.00, 'per kg', '/products/multani-mitti.jpg', 'Fuller earth', 'India'),
('red-chilli', 'Red Chilli', 'Spices', 200.00, 'per 100g', '/products/red-chilli.jpg', 'Dried red chilli', 'India'),
('jaggery-powder', 'Jaggery Powder', 'Sweeteners', 100.00, 'per kg', '/products/jaggery-powder.jpg', 'Powdered jaggery', 'India'),
('nattukaramani', 'Nattukaramani', 'Specialty', 250.00, 'per kg', '/products/nattukaramani.jpg', 'Village oil', 'India'),
('white-peas', 'White Peas', 'Legumes', 135.00, 'per kg', '/products/white-peas.jpg', 'Dried peas', 'India'),
('fried-gram', 'Fried Gram', 'Legumes', 160.00, 'per kg', '/products/fried-gram.jpg', 'Roasted chickpeas', 'India'),
('puffed-rice', 'Puffed Rice', 'Cereals', 70.00, 'per kg', '/products/puffed-rice.jpg', 'Murmura', 'India'),
('white-chick-peas', 'White Chick Peas', 'Legumes', 150.00, 'per kg', '/products/white-chick-peas.jpg', 'Kabuli chana', 'India')
ON CONFLICT (id) DO NOTHING;
